# Generated by Django 5.1.7 on 2025-03-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insidepoi',
            name='x_coor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insidepoi',
            name='y_coor',
            field=models.FloatField(),
        ),
    ]
